server:
  port: 7777
  servlet:
    context-path: /appcenter
  tomcat:
    # tomcat 启动的最大线程数，即同时处理的任务个数
    max-threads: 1000
    # 请求的最大连接数
    max-connections: 20000
    # 连接超时时间
    connection-timeout: 1000
    # tomcat 启动的线程数达到最大时，接受排队的请求个数  当队列已满时，任何的连接请求都将被拒绝
    accept-count: 1000
    # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
    min-spare-threads: 100
    # 设置tomcat工作路径
    basedir: ./
    accesslog:
      enabled: true
      directory: service-logs
      rotate: true
      pattern: '%t %a "%r" %s %D ms'
  # 关闭Whitelabel Error Page
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: WebAppcenterService
  profiles:
    active: dev
  # 让404抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 关闭静态资源映射
  resources:
    add-mappings: false
  # caffeine配置
#  cache:
#    type: CAFFEINE
#    caffeine:
#      # 初始缓存空间容量50 最大容量100
#      spec: initialCapacity=64, maximumSize=128,expireAfterWrite=1H
  # mongoDB配置
  data:
    mongodb:
      uri: mongodb://localhost:27020/www-yeshen-mis
  # 邮箱配置
  mail:
    enable: true
    host: smtp.qq.com
    username: aaa@qq.com
    password: 123456
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  thymeleaf:
    check-template: false
    check-template-location: false
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
# 添加健康检查
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /manage
      exposure:
        include: 'health,loggers,threaddump,heapdump,env'
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    threaddump:
      enabled: true
    heapdump:
      enabled: true
    env:
      enabled: true
# caffeine配置
cache-config:
  specs:
    XMLInfo:
      expire-time: 168
      max-size: 16
    game_download_top:
      expire-time: 1
      max-size: 32
    all_banner:
      expire-time: 1
      max-size: 32
    all_label:
      expire-time: 1
      max-size: 32
    recommend_game:
      expire-time: 1
      max-size: 32