server:
  port: 8012
  servlet:
    context-path: /appcenter
  tomcat:
    # 设置tomcat工作路径
    basedir: ./
    accesslog:
      enabled: true
      directory: etl-logs
      rotate: true
      pattern: '%t %a "%r" %s %D ms'
spring:
  application:
    name: WebAppcenterETL
  profiles:
    active: dev
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
# oss
aliyun:
  oss:
    access-key-id: root
    access-key-secret: 123456
    bucket-name: aaa
    endpoint: aaa.com
    hostname: http://aaa.com